apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubebuilder-webhook-serving-cert
  namespace: kubebuilder-webhook-system
spec:
  dnsNames:
  - kubebuilder-webhook-webhook-service.kubebuilder-webhook-system.svc
  - kubebuilder-webhook-webhook-service.kubebuilder-webhook-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kubebuilder-webhook-selfsigned-issuer
  secretName: webhook-server-cert