apiVersion: v1
kind: Service
metadata:
  name: nddp-svc-nddp-srl3-8882f12f5a3e-webhook
  namespace: ndd-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    webhook: nddp-svc-nddp-srl3-8882f12f5a3e-webhook